// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY6aiBEtl2WpTY8EjsD6XByfrVaBkLsHo',
    appId: '1:431260677420:web:7006f08c98cb41cb672889',
    messagingSenderId: '431260677420',
    projectId: 'saless123',
    authDomain: 'saless123.firebaseapp.com',
    databaseURL: 'https://saless123-default-rtdb.firebaseio.com',
    storageBucket: 'saless123.appspot.com',
    measurementId: 'G-ECZPN7HYHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_ROsJi5tveUNK8xkSh208JvbmJ6mtu8',
    appId: '1:431260677420:android:51bccaa215c00a05672889',
    messagingSenderId: '431260677420',
    projectId: 'saless123',
    databaseURL: 'https://saless123-default-rtdb.firebaseio.com',
    storageBucket: 'saless123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpsP2j2dla13hCAXuWbP7iCdG-XroX37Y',
    appId: '1:431260677420:ios:7c1db46fae4f9b95672889',
    messagingSenderId: '431260677420',
    projectId: 'saless123',
    databaseURL: 'https://saless123-default-rtdb.firebaseio.com',
    storageBucket: 'saless123.appspot.com',
    iosBundleId: 'com.example.sales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpsP2j2dla13hCAXuWbP7iCdG-XroX37Y',
    appId: '1:431260677420:ios:7c1db46fae4f9b95672889',
    messagingSenderId: '431260677420',
    projectId: 'saless123',
    databaseURL: 'https://saless123-default-rtdb.firebaseio.com',
    storageBucket: 'saless123.appspot.com',
    iosBundleId: 'com.example.sales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY6aiBEtl2WpTY8EjsD6XByfrVaBkLsHo',
    appId: '1:431260677420:web:d79fa640465321dd672889',
    messagingSenderId: '431260677420',
    projectId: 'saless123',
    authDomain: 'saless123.firebaseapp.com',
    databaseURL: 'https://saless123-default-rtdb.firebaseio.com',
    storageBucket: 'saless123.appspot.com',
    measurementId: 'G-P4C31GWVY3',
  );
}
